// Operaciones Autenticacion
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

// Operaciones Presupuestos
export const FORMULARIO_PRESUPUESTO = 'FORMULARIO_PRESUPUESTO'
export const OBTENER_PRESUPUESTOS = 'OBTENER_PRESUPUESTOS'
export const AGREGAR_PRESUPUESTO = 'AGREGAR_PRESUPUESTO';
export const ACTUALIZAR_PRESUPUESTO = 'ACTUALIZAR_PRESUPUESTO';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const PRESUPUESTO_ACTUAL = 'PRESUPUESTO_ACTUAL';
export const ELIMINAR_PRESUPUESTO = 'ELIMINAR_PRESUPUESTO';
export const PRESUPUESTO_ERROR = 'PRESUPUESTO_ERROR';

// Operaciones Gastos
export const GASTOS_PRESUPUESTO = 'GASTOS_LISTA';
export const AGREGAR_GASTO = 'AGREGAR_GASTO';
export const VALIDAR_GASTO = 'VALIDAR_GASTO';
export const ELIMINAR_GASTO = 'ELIMINAR_GASTO';
export const GASTO_ACTUAL = 'GASTO_ACTUAL';
export const ACTUALIZAR_GASTO = 'ACTUALIZAR_GASTO';
export const LIMPIAR_GASTO = 'LIMPIAR_GASTO';